### ISSUE TITLE
Submitting Request

### ISSUE THREAD

**Issue by Ipv6Python** [themains/trusted#1]
this is an awesome workaround for what I'm looking for. When there is output with an UNKNOWN Category returned. Is there a way to submit a request through the script?

**Comment by soodoku** [comment]
Pleased that this has been useful for you. @Ipv6Python: I didn't get your question, though. The reason the category is unknown is because Trusted API doesn't have a judgment about the domain. If you are looking to get categories for domains, our more comprehensive solution = https://github.com/themains/pydomains

**Comment by Ipv6Python** [comment]
thank you for getting back.  The script can validate the URL and get back a category. So, say if the category is unknown there is an Option in the trustedSource site to submit it for review. Can we include that step in the script?

**Comment by soodoku** [comment]
Right. This is non-traditional access to a non-API. And I built it to solve one small thing for myself. This is the long way of saying that I don't have plans to add this functionality. But feel free to PR to add to it as you see fit.
